import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  mediaDetails,
}: {
  children: React.ReactNode;
  mediaDetails: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center gap-6 justify-start p-24">
          {children}
          {mediaDetails}
        </main>
      </body>
    </html>
  );
}
